//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiThi
    {
        public int IDBaiThi { get; set; }
        public Nullable<int> IDLH { get; set; }
        public Nullable<int> IDDeThi { get; set; }
        public Nullable<int> IDND { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<int> IDViTri { get; set; }
        public Nullable<double> DiemSo { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<int> LanThi { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
