//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDT_ThanhVienTieuBan
    {
        public int ID { get; set; }
        public Nullable<int> TieuBan_ID { get; set; }
        public Nullable<int> NhanVien_ID { get; set; }
        public Nullable<int> ViTriKNL_ID { get; set; }
        public Nullable<int> ViTriTieuBan_ID { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<System.DateTime> NgayDenHanCapNhatLai { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> NhanVienThem_ID { get; set; }
        public Nullable<int> NhanVienSua_ID { get; set; }
    }
}
