//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoiDeThi
    {
        public int IDCauHoiDeThi { get; set; }
        public Nullable<int> IDCauHoi { get; set; }
        public Nullable<int> IDDeThi { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
        public virtual DeThi DeThi { get; set; }
    }
}
