//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBaiThi
    {
        public int IDCTBT { get; set; }
        public Nullable<int> IDBaiThi { get; set; }
        public Nullable<int> IDCauHoi { get; set; }
        public Nullable<int> IDDapAnDung { get; set; }
        public Nullable<int> IDDApAnNV { get; set; }
        public Nullable<double> Diem { get; set; }
    }
}
