//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTLVDT
    {
        public int IDCTLVDT { get; set; }
        public string TenCTLVDT { get; set; }
        public Nullable<int> LVDTID { get; set; }
    
        public virtual LinhVucDT LinhVucDT { get; set; }
    }
}
