//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeNghiKCCD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeNghiKCCD()
        {
            this.PhieuXacNhanKCCD = new HashSet<PhieuXacNhanKCCD>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NoiDungKCCDID { get; set; }
        public Nullable<int> LinhVucID { get; set; }
        public Nullable<int> NhomNangLucID { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<int> HuongDan1 { get; set; }
        public Nullable<int> ViTriID1 { get; set; }
        public Nullable<int> HuongDan2 { get; set; }
        public Nullable<int> ViTriID2 { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<System.DateTime> NgayXN { get; set; }
        public Nullable<int> isKiemTra { get; set; }
        public Nullable<int> DeThiID { get; set; }
    
        public virtual NoiDungDTKCCD NoiDungDTKCCD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXacNhanKCCD> PhieuXacNhanKCCD { get; set; }
    }
}
