//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeThi()
        {
            this.CauHoiDeThi = new HashSet<CauHoiDeThi>();
        }
    
        public int IDDeThi { get; set; }
        public string MaDe { get; set; }
        public string TenDe { get; set; }
        public Nullable<double> DiemChuan { get; set; }
        public Nullable<int> ThoiGianLamBai { get; set; }
        public Nullable<int> IDND { get; set; }
        public Nullable<int> GVID { get; set; }
        public Nullable<int> TongSoCau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHoiDeThi> CauHoiDeThi { get; set; }
        public virtual NoiDungDT NoiDungDT { get; set; }
    }
}
