//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhBienVT
    {
        public int ID { get; set; }
        public Nullable<int> IDVT { get; set; }
        public Nullable<int> SLDinhBien { get; set; }
        public Nullable<int> NSTapSu { get; set; }
        public Nullable<int> NSTrong { get; set; }
        public Nullable<System.DateTime> TGBoNhiem { get; set; }
        public Nullable<int> NSVTKhac { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
