//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMST_PheDuyet
    {
        public int ID { get; set; }
        public Nullable<int> ID_DeXuat { get; set; }
        public Nullable<int> NguoiDeXuat { get; set; }
        public Nullable<int> TinhTrang_NDX { get; set; }
        public Nullable<System.DateTime> NgayXL_NDX { get; set; }
        public Nullable<int> ID_TPBP { get; set; }
        public Nullable<int> TinhTrang_TPBP { get; set; }
        public Nullable<System.DateTime> NgayXL_TPBP { get; set; }
        public Nullable<int> ID_PCHN { get; set; }
        public Nullable<int> TinhTrang_PCHN { get; set; }
        public Nullable<System.DateTime> NgayXL_PCHN { get; set; }
    }
}
