//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMST_DeXuat_ChiTiet
    {
        public int IDCT { get; set; }
        public string TenDeTai { get; set; }
        public Nullable<System.DateTime> ThoiGian_ApDung { get; set; }
        public Nullable<int> ID_PhamVi_ApDung { get; set; }
        public Nullable<int> ID_TinhTrang_ApDung { get; set; }
        public Nullable<int> TinhTrang_TacGia { get; set; }
        public string ThucTrang { get; set; }
        public string CachThucThucHien { get; set; }
        public string VanDeGapPhai { get; set; }
        public string UuDiem { get; set; }
        public string NhuocDiem { get; set; }
        public string ThuanLoi { get; set; }
        public string KhoKhan { get; set; }
        public Nullable<int> ID_TinhTrangHieuQua { get; set; }
        public string LoiIchXaHoi { get; set; }
        public string DeXuatKienNghi { get; set; }
        public Nullable<int> TinhTrang_CamKet { get; set; }
        public Nullable<int> ID_DeXuat { get; set; }
    
        public virtual DMST_DeXuat DMST_DeXuat { get; set; }
    }
}
