//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMST_DeXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMST_DeXuat()
        {
            this.DMST_DeXuat_ChiTiet = new HashSet<DMST_DeXuat_ChiTiet>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_HoatDong { get; set; }
        public Nullable<int> ID_LinhVuc { get; set; }
        public Nullable<int> ID_NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMST_DeXuat_ChiTiet> DMST_DeXuat_ChiTiet { get; set; }
    }
}
