//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMST_TacGia
    {
        public int ID { get; set; }
        public Nullable<int> ID_TacGia { get; set; }
        public Nullable<int> IsNhomTacGia { get; set; }
        public Nullable<int> ID_DeXuat { get; set; }
        public Nullable<double> TiLeDongGop { get; set; }
    }
}
