//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSachDG
    {
        public int IDDS { get; set; }
        public string MaNV { get; set; }
        public string NVDG { get; set; }
        public Nullable<int> IDKNL { get; set; }
    }
}
