//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DV_ViTri
    {
        public int IDVT { get; set; }
        public string MaViTri { get; set; }
        public string TenViTri { get; set; }
        public string CapQuanLy { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
