//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCCD_CTBaiThi
    {
        public int IDCT { get; set; }
        public Nullable<int> IDBT { get; set; }
        public Nullable<int> IDCauHoi { get; set; }
        public Nullable<int> DapAnHV { get; set; }
        public Nullable<int> IDDAĐung { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual KCCD_CauHoi KCCD_CauHoi { get; set; }
        public virtual KCCD_BaiThi KCCD_BaiThi { get; set; }
    }
}
