//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCCD_DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KCCD_DeThi()
        {
            this.KCCD_CauHoi = new HashSet<KCCD_CauHoi>();
        }
    
        public int ID { get; set; }
        public string MaDe { get; set; }
        public string TenDe { get; set; }
        public Nullable<double> DiemChuan { get; set; }
        public Nullable<int> KCCDID { get; set; }
        public Nullable<int> CTDT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KCCD_CauHoi> KCCD_CauHoi { get; set; }
    }
}
