//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCCD_BaiThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KCCD_BaiThi()
        {
            this.KCCD_CTBaiThi = new HashSet<KCCD_CTBaiThi>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<int> KCCDID { get; set; }
        public Nullable<int> DeThiID { get; set; }
        public Nullable<double> Diem { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public Nullable<int> LanThi { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> DeNghiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KCCD_CTBaiThi> KCCD_CTBaiThi { get; set; }
    }
}
