//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhungNangLuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhungNangLuc()
        {
            this.KNL_KQ = new HashSet<KNL_KQ>();
        }
    
        public int IDNL { get; set; }
        public string TenNL { get; set; }
        public Nullable<int> IDLoaiNL { get; set; }
        public Nullable<int> IDVT { get; set; }
        public Nullable<int> IDPB { get; set; }
        public Nullable<int> DinhMuc { get; set; }
        public Nullable<int> IsDanhGia { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> IsDuyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KNL_KQ> KNL_KQ { get; set; }
    }
}
