//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNL_DGiaTC
    {
        public int ID { get; set; }
        public Nullable<int> IDVT { get; set; }
        public Nullable<int> IDVTDGTT { get; set; }
        public Nullable<int> IDVTDGTC { get; set; }
    }
}
