//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNL_KQ
    {
        public int IDKQ { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<int> IDNL { get; set; }
        public Nullable<int> IDNVDG { get; set; }
        public Nullable<int> DiemDG { get; set; }
        public Nullable<System.DateTime> ThangDG { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
        public string Note { get; set; }
        public Nullable<int> DiemDM { get; set; }
        public Nullable<int> KQID { get; set; }
        public Nullable<int> VTID { get; set; }
        public Nullable<int> DiemTuDG { get; set; }
        public Nullable<System.DateTime> NgayTuDG { get; set; }
        public Nullable<int> IDNguoiDG_Lan1 { get; set; }
        public Nullable<int> DiemDG_Lan1 { get; set; }
        public Nullable<System.DateTime> NgayDG_Lan1 { get; set; }
    }
}
