//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNL_To
    {
        public int IDTo { get; set; }
        public string TenTo { get; set; }
        public string MaTo { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<int> IDPhanXuong { get; set; }
        public Nullable<int> IDKhoi { get; set; }
    }
}
