//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNL_PheDuyetKNL
    {
        public int ID { get; set; }
        public Nullable<int> IDVT { get; set; }
        public Nullable<System.DateTime> NgayTrinhKy { get; set; }
        public Nullable<int> ID_NguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string File_KNL { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> ID_NguoiTao { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
