//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNL_LSDG
    {
        public int IDLS { get; set; }
        public Nullable<int> NVID { get; set; }
        public Nullable<int> VTID { get; set; }
        public Nullable<System.DateTime> ThangDG { get; set; }
        public Nullable<System.DateTime> NgayDGGN { get; set; }
        public Nullable<int> DAT { get; set; }
        public Nullable<int> KDAT { get; set; }
        public Nullable<int> VUOT { get; set; }
        public Nullable<int> KDGia { get; set; }
        public Nullable<int> CHUADG { get; set; }
        public Nullable<int> TONGNL { get; set; }
    
        public virtual ViTriKNL ViTriKNL { get; set; }
    }
}
