//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_ChiTietThuong
    {
        public int ID { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public string TapThe { get; set; }
        public Nullable<int> ID_NoiDungThuong { get; set; }
        public Nullable<decimal> GiaTriThuong { get; set; }
    }
}
