//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_DanhSachKhenThuong
    {
        public int ID { get; set; }
        public string MNV { get; set; }
        public string HoTen { get; set; }
        public string TapThe { get; set; }
        public string DonVi { get; set; }
        public string NoiDungKhenThuong { get; set; }
        public string LoaiKhenThuong { get; set; }
        public string SoQuyetDinh { get; set; }
        public Nullable<double> GiaTriThuong { get; set; }
        public Nullable<double> GiaTriLamLoi { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> ID_NoiDungThuong { get; set; }
    }
}
