//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_HinhAnh
    {
        public int ID { get; set; }
        public string MaDoiTuong { get; set; }
        public string LoaiDoiTuong { get; set; }
        public string AvatarPath { get; set; }
    }
}
