//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_NoiDungThuong
    {
        public int ID { get; set; }
        public string SoQuyetDinh { get; set; }
        public Nullable<int> ID_LoaiKhenThuong { get; set; }
        public string NoiDungKhenThuong { get; set; }
        public Nullable<System.DateTime> NgayQuyetDinh { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<decimal> GiaTriLamLoi { get; set; }
        public Nullable<decimal> TongTienThuong { get; set; }
        public string BannerImage { get; set; }
    }
}
