//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.XNHocTap = new HashSet<XNHocTap>();
        }
    
        public int IDLH { get; set; }
        public string MaLH { get; set; }
        public string TenLH { get; set; }
        public Nullable<int> NDID { get; set; }
        public Nullable<int> QuyDT { get; set; }
        public Nullable<int> NamDT { get; set; }
        public Nullable<System.DateTime> TGBDLH { get; set; }
        public Nullable<System.DateTime> TGKTLH { get; set; }
        public Nullable<int> GVID { get; set; }
        public Nullable<int> IDDeThi { get; set; }
        public Nullable<bool> ToChucThi { get; set; }
        public Nullable<int> NCDT_ID { get; set; }
        public Nullable<int> CTDT_ID { get; set; }
        public string NoiDungTrichYeu { get; set; }
        public string DiaDiemDT { get; set; }
        public string ThoiLuongDT { get; set; }
        public Nullable<int> DonVi_GV { get; set; }
        public Nullable<int> BoPhan_ID { get; set; }
        public Nullable<int> NguoiTao_ID { get; set; }
        public Nullable<int> NguoiKiemTra_ID { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
        public Nullable<int> IsCoCTDT { get; set; }
    
        public virtual NoiDungDT NoiDungDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XNHocTap> XNHocTap { get; set; }
    }
}
