//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.KNL_PheDuyetKNL = new HashSet<KNL_PheDuyetKNL>();
            this.KNL_PheDuyetKNL1 = new HashSet<KNL_PheDuyetKNL>();
            this.SH_ChuongTrinhDT = new HashSet<SH_ChuongTrinhDT>();
            this.SH_NhuCauDT = new HashSet<SH_NhuCauDT>();
            this.XNHocTap = new HashSet<XNHocTap>();
        }
    
        public int ID { get; set; }
        public string MaNV { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string HoTenKhongDau { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<int> IDTinhTrangLV { get; set; }
        public Nullable<int> IDViTri { get; set; }
        public Nullable<bool> IsGV { get; set; }
        public Nullable<int> IDQuyen { get; set; }
        public Nullable<int> IDVTKNL { get; set; }
        public Nullable<int> IDQuyenKNL { get; set; }
        public string MaViTri { get; set; }
        public Nullable<int> IDKip { get; set; }
        public string ChuKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KNL_PheDuyetKNL> KNL_PheDuyetKNL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KNL_PheDuyetKNL> KNL_PheDuyetKNL1 { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual TinhTrangLV TinhTrangLV { get; set; }
        public virtual Vitri Vitri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SH_ChuongTrinhDT> SH_ChuongTrinhDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SH_NhuCauDT> SH_NhuCauDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XNHocTap> XNHocTap { get; set; }
    }
}
