//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiDungDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NoiDungDT()
        {
            this.DeThi = new HashSet<DeThi>();
            this.LopHoc = new HashSet<LopHoc>();
            this.SH_NhuCauDT = new HashSet<SH_NhuCauDT>();
        }
    
        public int IDND { get; set; }
        public string MaND { get; set; }
        public string NoiDung { get; set; }
        public string VideoND { get; set; }
        public string ImageND { get; set; }
        public Nullable<int> BPLID { get; set; }
        public Nullable<int> LVDTID { get; set; }
        public Nullable<int> IDCTLVDT { get; set; }
        public Nullable<int> ThoiLuongDT { get; set; }
        public string FileDinhKem { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> isOrder { get; set; }
        public Nullable<int> isNQ { get; set; }
        public Nullable<int> IDNguonGV { get; set; }
        public Nullable<int> IDHoatDongDT { get; set; }
        public Nullable<int> IDPhuongPhapDT { get; set; }
        public Nullable<int> IDNhomNL { get; set; }
        public Nullable<int> IDPhanLoaiDT { get; set; }
        public Nullable<int> LoaiNCDT_ID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeThi> DeThi { get; set; }
        public virtual LinhVucDT LinhVucDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHoc> LopHoc { get; set; }
        public virtual SH_HoatDongDT SH_HoatDongDT { get; set; }
        public virtual SH_NguonGV SH_NguonGV { get; set; }
        public virtual NhomNLKCCD NhomNLKCCD { get; set; }
        public virtual SH_PhanLoaiNDDT SH_PhanLoaiNDDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SH_NhuCauDT> SH_NhuCauDT { get; set; }
    }
}
