//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NQ_Chuong
    {
        public int ID { get; set; }
        public string MaChuong { get; set; }
        public string TenChuong { get; set; }
        public Nullable<int> isOrder { get; set; }
        public Nullable<int> SLTG { get; set; }
        public Nullable<int> SLHT { get; set; }
        public Nullable<int> SLHTFile { get; set; }
    }
}
