//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NQ_KetQua
    {
        public int ID { get; set; }
        public Nullable<int> NDDTID { get; set; }
        public Nullable<int> XNTG { get; set; }
        public Nullable<int> XNHT { get; set; }
        public Nullable<int> XNHTFile { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<System.DateTime> NgayTG { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    }
}
