//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongBan()
        {
            this.NhanVien = new HashSet<NhanVien>();
            this.SH_ChuongTrinhDT = new HashSet<SH_ChuongTrinhDT>();
            this.SH_NhuCauDT = new HashSet<SH_NhuCauDT>();
            this.QTUX_LichHoc = new HashSet<QTUX_LichHoc>();
        }
    
        public int IDPhongBan { get; set; }
        public string TenPhongBan { get; set; }
        public string MaPB { get; set; }
        public string API_MaPB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SH_ChuongTrinhDT> SH_ChuongTrinhDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SH_NhuCauDT> SH_NhuCauDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QTUX_LichHoc> QTUX_LichHoc { get; set; }
    }
}
