//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QT_BaiKiemTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QT_BaiKiemTra()
        {
            this.QT_CTBaiKiemTra = new HashSet<QT_CTBaiKiemTra>();
        }
    
        public int IDKT { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<int> QTHDID { get; set; }
        public Nullable<double> Diem { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
        public Nullable<System.DateTime> NgayKTTT { get; set; }
        public Nullable<int> LanKT { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> LuotKiemTra { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
    
        public virtual QT_NoiDungQT QT_NoiDungQT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QT_CTBaiKiemTra> QT_CTBaiKiemTra { get; set; }
    }
}
