//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QT_CTBaiKiemTra
    {
        public int IDCTKT { get; set; }
        public Nullable<int> IDKiemTra { get; set; }
        public Nullable<int> IDCauHoi { get; set; }
        public Nullable<int> DapAnHV { get; set; }
        public string IDDAĐung { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual QT_BaiKiemTra QT_BaiKiemTra { get; set; }
        public virtual QT_CauHoiQT QT_CauHoiQT { get; set; }
    }
}
