//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QT_CauHoiQT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QT_CauHoiQT()
        {
            this.QT_CTBaiKiemTra = new HashSet<QT_CTBaiKiemTra>();
        }
    
        public int IDCH { get; set; }
        public string NoiDungCH { get; set; }
        public string DapAnA { get; set; }
        public string DapAnB { get; set; }
        public string DapAnC { get; set; }
        public string DapAnD { get; set; }
        public Nullable<int> IDDAĐung { get; set; }
        public Nullable<int> QTHDID { get; set; }
    
        public virtual QT_NoiDungQT QT_NoiDungQT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QT_CTBaiKiemTra> QT_CTBaiKiemTra { get; set; }
    }
}
