//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QT_NoiDungQT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QT_NoiDungQT()
        {
            this.QT_BaiKiemTra = new HashSet<QT_BaiKiemTra>();
            this.QT_CauHoiQT = new HashSet<QT_CauHoiQT>();
            this.QT_FileQT = new HashSet<QT_FileQT>();
            this.QT_PhanQuyen = new HashSet<QT_PhanQuyen>();
            this.QT_VanBanLQ = new HashSet<QT_VanBanLQ>();
        }
    
        public int IDQTHD { get; set; }
        public string MaHieu { get; set; }
        public string TenQTHD { get; set; }
        public Nullable<int> IDLoaiQTHD { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<int> IDLVDT { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public Nullable<System.DateTime> NgayHetHieuLuc { get; set; }
        public Nullable<double> DiemChuan { get; set; }
        public Nullable<int> LanCapNhat { get; set; }
        public string NoiDungCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QT_BaiKiemTra> QT_BaiKiemTra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QT_CauHoiQT> QT_CauHoiQT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QT_FileQT> QT_FileQT { get; set; }
        public virtual QT_LoaiQT QT_LoaiQT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QT_PhanQuyen> QT_PhanQuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QT_VanBanLQ> QT_VanBanLQ { get; set; }
    }
}
