//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QTUX_LichHoc
    {
        public int ID { get; set; }
        public Nullable<int> IsKichHoat { get; set; }
        public int LoaiKhuonKy { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> NgayTrongTuan { get; set; }
        public Nullable<int> NgayTrongThang { get; set; }
        public Nullable<int> ChiSoThang { get; set; }
    
        public virtual DeThi DeThi { get; set; }
        public virtual NoiDungDT NoiDungDT { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
