//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_ChuongTrinhDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SH_ChuongTrinhDT()
        {
            this.SH_ChiTietCTDT = new HashSet<SH_ChiTietCTDT>();
        }
    
        public int IDCTDT { get; set; }
        public string TenChuongTrinhDT { get; set; }
        public string NoiDungTrichYeu { get; set; }
        public Nullable<int> ThoiLuongDT { get; set; }
        public string FileDinhKem { get; set; }
        public Nullable<int> IDPhuongPhapDT { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string FileCTDT { get; set; }
        public Nullable<int> IDKiemTra { get; set; }
        public string DoiTuongDT { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> ID_NguoiTao { get; set; }
        public Nullable<int> ID_NoiDungDT { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual NoiDungDT NoiDungDT { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SH_ChiTietCTDT> SH_ChiTietCTDT { get; set; }
    }
}
