//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_ChiTietCTDT
    {
        public int ID { get; set; }
        public string NoiDungDT { get; set; }
        public Nullable<int> ThoiGianDT { get; set; }
        public string YeuCau { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> ID_CTDT { get; set; }
    }
}
