//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_ChiTietTCDT
    {
        public int ID { get; set; }
        public Nullable<int> CTDT_ID { get; set; }
        public Nullable<int> ID_GVCty { get; set; }
        public string MaNV_GV { get; set; }
        public string HoTenGV { get; set; }
        public string ViTriCV_GV { get; set; }
        public string DonVi_GV { get; set; }
    }
}
