//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_ChiTiet_NCDT
    {
        public int ID { get; set; }
        public Nullable<int> NhuCauDT_ID { get; set; }
        public string DoiTuongDT { get; set; }
        public Nullable<int> SoLuongNguoi { get; set; }
        public Nullable<int> GiangVien_ID { get; set; }
        public string GiangVien_HoTen { get; set; }
        public string GiangVien_Vitri { get; set; }
        public Nullable<int> ThoiGian_DT { get; set; }
        public Nullable<int> ThoiLuong_DT { get; set; }
        public string DiaDiemDT { get; set; }
        public string GhiChu { get; set; }
        public string DonViDT { get; set; }
    
        public virtual SH_NhuCauDT SH_NhuCauDT { get; set; }
    }
}
