//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_ChuongTrinhDT
    {
        public int IDCTDT { get; set; }
        public string TenCTDT { get; set; }
        public string VideoND { get; set; }
        public string ImageND { get; set; }
        public Nullable<int> LVDTID { get; set; }
        public Nullable<int> ThoiLuongDT { get; set; }
        public string FileDinhKem { get; set; }
        public Nullable<int> IDNguonGV { get; set; }
        public Nullable<int> IDHoatDongDT { get; set; }
        public Nullable<int> IDPhuongPhapDT { get; set; }
        public Nullable<int> IDNhomNL { get; set; }
        public Nullable<int> IDPhanLoaiDT { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string FileCTDT { get; set; }
        public string NoiDungTrichYeu { get; set; }
        public string DoiTuongDT { get; set; }
        public Nullable<int> IDKiemTra { get; set; }
    }
}
