//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_HoSoDaoTao
    {
        public int ID { get; set; }
        public Nullable<int> LHID { get; set; }
        public Nullable<System.DateTime> NgayBDThucTe { get; set; }
        public Nullable<System.DateTime> NgayKTThucTe { get; set; }
        public Nullable<int> ID_GiangVien { get; set; }
        public string HoTenGV { get; set; }
        public string MaGiangVien { get; set; }
        public string DonViGV { get; set; }
        public Nullable<double> ThoiLuongDT { get; set; }
        public Nullable<int> ID_NguoiNopHS { get; set; }
        public Nullable<System.DateTime> NgayNopHS { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> ID_NguoiXuLy { get; set; }
        public Nullable<System.DateTime> NgayXuLy { get; set; }
    }
}
