//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_KyDuyetCTDT
    {
        public int ID { get; set; }
        public Nullable<int> ID_CTDT { get; set; }
        public Nullable<int> ID_NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> ID_NguoiKiemTra { get; set; }
        public Nullable<System.DateTime> NgayKTDuyet { get; set; }
        public Nullable<int> ID_TPBP { get; set; }
        public Nullable<System.DateTime> NgayTPBP { get; set; }
        public Nullable<int> ID_PCHN { get; set; }
        public Nullable<System.DateTime> NgayPCHN { get; set; }
        public Nullable<System.DateTime> NgayDuyetNDDT { get; set; }
        public Nullable<int> ID_NguoiDuyetNDDT { get; set; }
    }
}
