//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_ViTri_NDDT
    {
        public int ID { get; set; }
        public Nullable<int> Vitri_ID { get; set; }
        public Nullable<int> NoiDungDT_ID { get; set; }
        public Nullable<int> PhuongPhapDT_ID { get; set; }
        public Nullable<int> NCDT_ID { get; set; }
        public Nullable<int> TinhTrang_NCDT { get; set; }
    }
}
