//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_KyLuat
    {
        public int ID { get; set; }
        public string TB_TieuDe { get; set; }
        public Nullable<int> TB_Thang { get; set; }
        public Nullable<int> TB_Nam { get; set; }
        public string TB_File { get; set; }
    }
}
