//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViTriKNL
    {
        public int IDVT { get; set; }
        public string TenViTri { get; set; }
        public string MaViTri { get; set; }
        public Nullable<int> IDPB { get; set; }
        public Nullable<int> IDKhoi { get; set; }
        public Nullable<int> IDPX { get; set; }
        public Nullable<int> IDNhom { get; set; }
        public Nullable<int> IDTo { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> IDVTParent { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    }
}
