//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XNHocTap
    {
        public int IDHT { get; set; }
        public Nullable<int> NVID { get; set; }
        public Nullable<int> LHID { get; set; }
        public Nullable<System.DateTime> NgayTG { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
        public Nullable<bool> XNTG { get; set; }
        public Nullable<bool> XNHT { get; set; }
        public Nullable<int> PBID { get; set; }
        public Nullable<int> VTID { get; set; }
        public Nullable<double> DiemOnline { get; set; }
        public Nullable<double> DiemLyThuyet { get; set; }
        public Nullable<double> DiemThucHanh { get; set; }
        public Nullable<double> DiemVanDap { get; set; }
        public Nullable<int> KetLuan { get; set; }
        public Nullable<int> IDND { get; set; }
        public Nullable<int> ID_PhuongPhapDT { get; set; }
        public string LyDoKhongTGia { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
    }
}
